

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author JENNY
 */
public class Bienvenido extends javax.swing.JFrame {

    /**
     * Creates new form Bienvenido
     */
    public Bienvenido() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
        
        
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        pro = new javax.swing.JMenu();
        mAB = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mRegistrar = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mInventario = new javax.swing.JMenuItem();
        mProovedor = new javax.swing.JMenu();
        mRegistrarproovedor = new javax.swing.JMenuItem();
        mPedidos = new javax.swing.JMenu();
        mPedidos_compras = new javax.swing.JMenuItem();
        ventas = new javax.swing.JMenu();
        mRealizarVentas = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mReporte = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        cerrarsesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(590, 440));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(560, 418));

        jLabel1.setFont(new java.awt.Font("Freestyle Script", 0, 48)); // NOI18N
        jLabel1.setText("Papelería \"El tepeyac\"");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo 2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        pro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/stationery.png"))); // NOI18N
        pro.setText("Productos");

        mAB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/altas y bajas.png"))); // NOI18N
        mAB.setText("Altas y bajas");
        mAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mABActionPerformed(evt);
            }
        });
        pro.add(mAB);
        pro.add(jSeparator1);

        mRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrar producto.png"))); // NOI18N
        mRegistrar.setText("Registrar producto");
        mRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRegistrarActionPerformed(evt);
            }
        });
        pro.add(mRegistrar);
        pro.add(jSeparator3);

        mInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inventario.png"))); // NOI18N
        mInventario.setText("Inventario");
        mInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mInventarioActionPerformed(evt);
            }
        });
        pro.add(mInventario);

        jMenuBar1.add(pro);

        mProovedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proveedorr.png"))); // NOI18N
        mProovedor.setText("Proovedores");
        mProovedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mProovedorActionPerformed(evt);
            }
        });

        mRegistrarproovedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proveed.png"))); // NOI18N
        mRegistrarproovedor.setText("Regitrar proovedor");
        mRegistrarproovedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRegistrarproovedorActionPerformed(evt);
            }
        });
        mProovedor.add(mRegistrarproovedor);

        jMenuBar1.add(mProovedor);

        mPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/compras.png"))); // NOI18N
        mPedidos.setText("compras");
        mPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPedidosActionPerformed(evt);
            }
        });

        mPedidos_compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pedidos.png"))); // NOI18N
        mPedidos_compras.setText("Pedidos");
        mPedidos_compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPedidos_comprasActionPerformed(evt);
            }
        });
        mPedidos.add(mPedidos_compras);

        jMenuBar1.add(mPedidos);

        ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/venta.png"))); // NOI18N
        ventas.setText("Ventas");
        ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasActionPerformed(evt);
            }
        });

        mRealizarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/metodo-de-pago.png"))); // NOI18N
        mRealizarVentas.setText("Realizar venta");
        mRealizarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRealizarVentasActionPerformed(evt);
            }
        });
        ventas.add(mRealizarVentas);
        ventas.add(jSeparator2);

        mReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.png"))); // NOI18N
        mReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mReporteActionPerformed(evt);
            }
        });
        ventas.add(mReporte);

        jMenuBar1.add(ventas);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuraciones.png"))); // NOI18N
        jMenu5.setText("Administrar_usuario");

        cerrarsesion.setText("Cerrar sesión");
        cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarsesionActionPerformed(evt);
            }
        });
        jMenu5.add(cerrarsesion);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarsesionActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null,"¿Estas seguro de salir de la aplicación?","Salir",JOptionPane.YES_NO_OPTION)==0)
        System.exit(0);
    }//GEN-LAST:event_cerrarsesionActionPerformed

    private void mRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRegistrarActionPerformed
        // TODO add your handling code here:
        Vproductos verregistrarcliente = new Vproductos();
        verregistrarcliente.setVisible(true);
        
    }//GEN-LAST:event_mRegistrarActionPerformed

    private void mProovedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mProovedorActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mProovedorActionPerformed

    private void mPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPedidosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mPedidosActionPerformed

    private void ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ventasActionPerformed

    private void mRegistrarproovedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRegistrarproovedorActionPerformed
        // TODO add your handling code here:
        Vproveedores registrarProovedor = new Vproveedores();
        registrarProovedor.setVisible(true);
    }//GEN-LAST:event_mRegistrarproovedorActionPerformed

    private void mPedidos_comprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPedidos_comprasActionPerformed
        // TODO add your handling code here:
        Vcompras pedidos_compras = new Vcompras();
        pedidos_compras.setVisible(true);
    }//GEN-LAST:event_mPedidos_comprasActionPerformed

    private void mRealizarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRealizarVentasActionPerformed
        // TODO add your handling code here:
        VVentas realizar_ventas = new VVentas();
        realizar_ventas.setVisible(true);
    }//GEN-LAST:event_mRealizarVentasActionPerformed

    private void mABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mABActionPerformed
        // TODO add your handling code here:
        Vproductos altasbajas = new Vproductos();
        altasbajas.setVisible(true);
    }//GEN-LAST:event_mABActionPerformed

    private void mInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mInventarioActionPerformed
        // TODO add your handling code here:
        Inventario inventario = new Inventario();
        inventario.setVisible(true);
    }//GEN-LAST:event_mInventarioActionPerformed

    private void mReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mReporteActionPerformed
        // TODO add your handling code here:
        Vreporte reporte = new Vreporte();
        reporte.setVisible(true);
    }//GEN-LAST:event_mReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cerrarsesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem mAB;
    private javax.swing.JMenuItem mInventario;
    private javax.swing.JMenu mPedidos;
    private javax.swing.JMenuItem mPedidos_compras;
    private javax.swing.JMenu mProovedor;
    private javax.swing.JMenuItem mRealizarVentas;
    private javax.swing.JMenuItem mRegistrar;
    private javax.swing.JMenuItem mRegistrarproovedor;
    private javax.swing.JMenuItem mReporte;
    private javax.swing.JMenu pro;
    private javax.swing.JMenu ventas;
    // End of variables declaration//GEN-END:variables
}
